apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "myapp.fullname" . }}-backend-v1
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
    app.kubernetes.io/version: "v1"  # Hardcoded version label
  annotations:
    sidecar.istio.io/inject: "true"
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: {{ include "myapp.name" . }}-backend
      version: v1  # Hardcoded version in selector
  template:
    metadata:
      labels:
        app: {{ include "myapp.name" . }}-backend
        version: v1  # Hardcoded version in label
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image }}"
          ports:
            - containerPort: {{ .Values.backend.port }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "myapp.fullname" . }}-backend-v2
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
    app.kubernetes.io/version: "v2"  # Hardcoded version label
  annotations:
    sidecar.istio.io/inject: "true"
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: {{ include "myapp.name" . }}-backend
      version: v2  # Hardcoded version in selector
  template:
    metadata:
      labels:
        app: {{ include "myapp.name" . }}-backend
        version: v2  # Hardcoded version in label
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image }}"
          ports:
            - containerPort: {{ .Values.backend.port }}
