apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  URLkaskks: bW9uZ29kYitzcnY6Ly9hbGltYXNvb2Q6ZUxLNDUyWnBtT0RFeml0VkB0ZXN0Y2x1c3Rlci5pa3lqdXIyLm1vbmdvZGIubmV0L0Jvb2tTdG9yZQ==
  URL: bW9uZ29kYjovL21vbmdvX2RiOjI3MDE3L0Jvb2tTdG9yZQ==
  JWT_SECRET: QWxpTWFzb29k
